# Generated by Django 3.1.dev20191223111756 on 2020-05-10 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userfeed', '0005_auto_20200510_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(related_name='liking_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
